- CODEOWNERS
> Changing codeowners file

- README.md
- openapi/generate_openapi.sh
- openapi/openapi.json
This PR resolves the failure of the Update Openapi action and updates the documentation with the right OpenAPI json file link.
> PAGOPA-345 fix: OpenAPI updating

- .github/workflows/deploy.yml
- openapi/openapi.json
- check & customize GitHub Action deploy
> ci: update deploy action [PAGOPA-349]

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-uat.yaml
- helm chart adjustment adding startup probe
> helm chart creation for uat and deploy [PAGOPA 351]

- helm/values-dev.yaml
Added chart configuration for the dev environment in Helm files.
- Updated main chart configuration in Chart.yaml
- Updated values.dev.yaml configuration for the DEV environment
Those changes were necessary for update the Helm configuration in AKS clusters.
Co-Authored-By: Angelo Caporaso <56113767+AngeloCaporaso@users.noreply.github.com>
> [PAGOPA-350] feat: Added chart config

- helm/values-uat.yaml
With this PR there will be inserted the missing ENV secrets about the connection strings in UAT environment.
Changed values.uat.yaml file including the missing secrets.
With this commit the missing secret, not inserted in the last commits, will be added.
> [PAGOPA-350] fix: added missing env secret

- .github/workflows/update_infra.yml
- .github/workflows/update_openapi.yml
- openapi/openapi.json
Fix update-infra and update-openapi in order to automatize open API updating on infrastructure.
> [PAGOPA 350] Fix GitHub Action 

- .devops/code-review-pipelines.yml
- Dockerfile
- docker/config/.env
- docker/docker-compose.yml
- docker/run_docker.sh
- integration-test/run_integration_test.sh
- integration-test/src/config/.env.local
- integration-test/src/step_definitions/support/api_config_client.js
- integration-test/src/step_definitions/support/steps.js
- openapi/openapi.json
Code review pipeline configuration
Necessary to perform correctly unit and smoke tests for the project
This tool has been tested using azure devops pipelines
> Pagopa 354 azure dev ops code review pipeline migration and check

- .github/workflows/update_infra.yml
Co-authored-by: Federico Ruzzier <FedericoRuzzier@users.noreply.github.com>
Co-authored-by: Andrea De Rinaldis <andrea-deri@users.noreply.github.com>
> ci: update-infra action [WIP]

- docker/docker-compose.yml
- helm/values-prod.yaml
Co-authored-by: Federico Ruzzier <FedericoRuzzier@users.noreply.github.com>
Co-authored-by: Andrea De Rinaldis <andrea-deri@users.noreply.github.com>
- tuning on helm values for production environment (replicas number, memory limits)
> ci: config prod settings PAGOPA-352 

- src/main/java/it/gov/pagopa/payments/config/SwaggerConfig.java
- adding the sorting algorithm for operations
- openapi update does not always return the result in the same order
> Fix operations order in swagger config

- .devops/code-review-pipelines.yml
Co-authored-by: Angelo Caporaso <AngeloCaporaso@users.noreply.github.com>
Co-authored-by: Andrea De Rinaldis <andrea-deri@users.noreply.github.com>
In this pr we refactored the code-review pipeline, so that it is executed only in the DEV environment. UAT and PROD are voluntarily excluded. 
This change was necessary to avoid reviewing code that had already passed the sonarcloud checks.
> refactoring code-review: code review only executed in dev

- README.md
With this commit, the README.md file is updated in order to add another known issue related to TestContainer container generation in docker-compose execution. 
The issue seems related to an error on writing permissions configuration for TestContainer library on Docker environment. This cannot be resolved with the current container configuration in Dockerfile and docker-compose.yaml for local environment on Mac devices, either with M1 chip and not. But it works correctly in DEV and UAT (at the moment of this PR).
So, due to the fact that seems an issue that can be avoided skipping the unit tests during `docker-compose` operation, the flag `test.skip=true` in `maven clean package` step will remains.
- Changed the README.md in order to notify the future developers to avoid the problem with …
> [PAGOPA-343] Fix Test Containers issue

- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
Adding null check on string length check when setting up a debt position
This was required for the whole process to work correctly
This has been tested using payments locally and apiconfig and gpd on uat
> fixing null pointer exception

- .identity/01_data.tf
- .identity/02_application_action_auth.tf
> [PAGOPA-777] fix: opex

- .identity/01_data.tf
- .identity/03_github_environment.tf
> fix: Opex prod

- .opex/env/prod/config.yaml
The opex tool (and so the github action) takes the `resource_type` as parameter, by default this parameter is set to `app-gateway` so it needs to be added and updated.
memo: in our case we use `../pagopa-p-apim` as the data source since both SOAP actions (from node) and REST Receipt endopoint (from EC) requests will be redirected to the APIM resource. While we could not have used `../pagopa-p-app-gw` because we would not have included the case of SOAP actions.
> [PAGOPA-777] fix opex

- .github/workflows/create_dashboard.yaml
- add step in `create_dashboard` to update `url` with base path. 
The path given as input to the dashboard tool is incorrect since the base path is missing. This PR adds a step to Github Action `create_dashboard` which does the replace of the `url` field.
> Fix dashboard paths

- .github/workflows/integration_test.yml
- helm/values-dev.yaml
- integration-test/src/step_definitions/support/utility/axios_common.js
- integration-test/src/step_definitions/support/utility/request_builders.js
These changes and this [pull request on pagopa-infra](https://github.com/pagopa/pagopa-infra/pull/928) fix the integration tests.
> fix: Update integration test payments [PAGOPA-994]

- .github/workflows/anchore.yml
- .github/workflows/check_pr.yml
- .github/workflows/code_review.yml
- .github/workflows/create_dashboard.yaml
- .github/workflows/deploy_with_github_runner.yml
- .github/workflows/integration_test.yml
- .github/workflows/release_deploy.yml
- .github/workflows/update_code.yml
- .github/workflows/update_infra.yml
> new actions

- .devops/performance-test-pipelines.yml
- performance-test/docker-compose.yaml
- performance-test/run_performance_test.sh
- performance-test/src/get_payment_V2_workflow.js
- performance-test/src/get_payment_workflow.js
- performance-test/src/payments_demand_notice.js
- performance-test/src/payments_workflow.js
- performance-test/src/payments_workflow.oneshot.js
- performance-test/src/send_rt_V2_workflow.js
- performance-test/src/send_rt_workflow.js
- performance-test/src/test-types/load.json
- performance-test/src/verify_payment_workflow.js
Addition of scripts in the load test section to test the V2 soap functions
This addition was required to properly test the newly implemented functions and their capabilities, confronted with the previous ones.
This has been tested through k6 and devops pipelines in environment DEV
> feat: adding V2 functions workflow for load tests PAGOPA-855

- .github/workflows/deploy_with_github_runner.yml
> fix gha runner

- src/main/resources/xsd/paForNode.xsd
> fix: transferType PAGOPA

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
- the condition was updated to include states `PO_PAID`, `PO_PARTIALLY_REPORTED` and `PO_REPORTED` in the white list and only consider state `PO_UNPAID` as exception case.
The application must return `422 UNPROCESSABLE_RECEIPT` only when the order has been paid. The states   `PO_PARTIALLY_REPORTED` and `PO_REPORTED` are consecutive to the state PAID, so it means that if the PO is in one of this states, it has already been paid.
> fix: Update PaymentsService UNPROCESSABLE_RECEIPT exception raising [PAGOPA-1238]

- src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
> fix: Update JUnit test [PAGOPA-1260] 

- src/main/java/it/gov/pagopa/payments/endpoints/PartnerEndpoint.java
> chore: Update log [PAGOPA-1286]

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- Upgrade helm chart version from `1.21.0` to `2.4.0`
- Update helm values according to [documentation](https://github.com/pagopa/aks-microservice-chart-blueprint/blob/main/README.md#breaking-changes)
> ci: Upgrade helm chart [PAGOPA-1288]

- .github/workflows/release_deploy.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- Update version input in release GHA
> ci: Update version input in release GHA

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
fix: Remove replace from transfer response V2
> fix: Remove replace from transfer response V2

- src/main/java/it/gov/pagopa/payments/exception/AppError.java
- src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
- src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
Adding limit to the max number of receipt per page on rest call
This addition is necessary to avoid out of memory exception
This has been tested manually and through junit tests
> fix: fixing max number of receipts PAGOPA-1321 

- src/main/java/it/gov/pagopa/payments/endpoints/PartnerEndpoint.java
- src/main/java/it/gov/pagopa/payments/endpoints/validation/SoapFaultDefinitionExceptionResolver.java
- src/main/java/it/gov/pagopa/payments/endpoints/validation/SoapMessageDispatcher.java
- src/main/java/it/gov/pagopa/payments/model/DebtPositionStatus.java
- src/main/java/it/gov/pagopa/payments/model/PaymentOptionStatus.java
- src/main/java/it/gov/pagopa/payments/model/PaymentsModelResponse.java
- src/main/java/it/gov/pagopa/payments/model/PaymentsTransferModelResponse.java
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
> [PAGOPA-1320-gpd-payments-analizzare-500] logging

- src/main/java/it/gov/pagopa/payments/model/PaymentOptionMetadataModel.java
- src/main/java/it/gov/pagopa/payments/model/PaymentOptionModel.java
- src/main/java/it/gov/pagopa/payments/model/PaymentOptionModelResponse.java
- src/main/java/it/gov/pagopa/payments/model/PaymentsModelResponse.java
- src/main/java/it/gov/pagopa/payments/model/PaymentsTransferModelResponse.java
- src/main/java/it/gov/pagopa/payments/model/TransferMetadataModel.java
- src/main/java/it/gov/pagopa/payments/model/TransferModelResponse.java
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
- src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
- src/test/resources/gpd/getPaymentOption.json
- src/test/resources/gpd/getPaymentOptionWithIncompleteAddress.json
- src/test/resources/gpd/getPaymentOption_PO_UNPAID.json
- src/test/resources/gpd/receiptPaymentOption.json
- Update `paGetPayment` e `paGetPaymentV2` response
- Update JUnit tests
> [PAGOPA-1352] feat: Update metadata

- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
Remove `dueDate` check on the particular Payment Option
`DebtPositionStatus` is `EXPIRED` when `maxDueDate` is has been reached. Thus, a Payment Option is payable as long as all Payment Option within the same Payment Position have not expired.
> [PAGOPA-1359] fix

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
- Update `generatePaGetPaymentResponse` methods
the metadata field is optional in the `paGetPaymentResponse` and `paGetPaymentV2Response`, so when it is not present in the PO it should not be added.
- Local environment manual test
- DEV environment integration test
> Fix GetPayment XML validation error

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
- src/main/resources/xsd-common/sac-common-types-1.0.xsd
- src/main/resources/xsd/paForNode.xsd
- src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
- Update XSD SANPv3.5.0 
- Align to SANPv3.5.0
> feat: Update XSD SANPv3.5.0 [PAGOPA-1390]

- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
> fix GetPaymentV1

- helm/values-prod.yaml
Update with `preferredDuringSchedulingIgnoredDuringExecution`:
_The scheduler tries to find a node that meets the rule. If a matching node is not available, the scheduler still schedules the Pod._
- weight is `100`, this specifies the weight of this anti-affinity rule.
- topology key is `topology.kubernetes.io/zone`, the node must have a label with the key `topology.kubernetes.io/zone`
This pod anti-affinity rule ensures that pods with the `app.kubernetes.io/instance: pagopagpdpayments` label are spread across different availability zones in the gps namespace.
> [BCDR] feat: Update podAntiAffinity

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/entity/ReceiptEntity.java
- src/main/java/it/gov/pagopa/payments/model/PaymentOptionModelResponse.java
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
- src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
- handled the unknown payment
- modified the implementation logics for saving payment receipts
- reporting anomalous behavior on unknown payment
> bug: [PagoPA-1476] unknown payment management

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/controller/receipt/IPaymentsController.java
- src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
`pageNum` and `pageSize` are no longer required fields and the default values are `0, 20` 
Improve QoS
> feat: update GET receipts default pagination [PAGOPA-1533] 

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
> fix: description mandatory field handling [PAGOPA-1566] 

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- integration-test/src/config/.env.dev
- integration-test/src/config/.env.local
- integration-test/src/config/.env.uat
- integration-test/src/features/gpd_payments.activate_phase.feature
- integration-test/src/features/gpd_payments.get_payment_phase.feature
- integration-test/src/features/gpd_payments.send_receipt_phase.feature
- integration-test/src/features/gpd_payments.verify_phase.feature
- integration-test/src/step_definitions/support/clients/api_config_client.js
- integration-test/src/step_definitions/support/logic/gpd_logic.js
- integration-test/src/step_definitions/support/steps.js
- integration-test/src/step_definitions/support/utility/request_builders.js
- openapi/openapi.json
- pom.xml
- made integration tests self-consistent
- when not already present in the DB, the data structures necessary for correct execution of the test are created
- manual execution in local and [dev](https://github.com/pagopa/pagopa-gpd-payments/actions/runs/8294925929/job/22700879392) env
> feat: [PagoPA-1497] adjustment integration test

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/model/PaymentsTransferModelResponse.java
- src/main/java/it/gov/pagopa/payments/model/TransferMetadataModel.java
- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
- src/test/java/it/gov/pagopa/payments/mock/PaGetPaymentReqMock.java
- src/test/java/it/gov/pagopa/payments/service/PartnerServiceTest.java
- Added IBANAPPOGGIO metadata
- verify the value of the transferType field in PAGOPA and creation of the IBANAPPOGGIO metadata
- manual and junit test
> feat: [PagoPA-1624] metadata IBANAPPOGGIO

- utils/requirements.txt
- utils/update_debtor_dev.py
- Update debtor fiscal code script
> chore: add update debtor py-script [PAGOPA-1650] 

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/utils/Validator.java
When mandatory fields as `company_name` or `description` are empty string (`""`) fix to `NA` value 
Compliance to SANP required fields
> fix: [PAGOPA-1680] validate when mandatory field is empty

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/payments/controller/receipt/IPaymentsController.java
- src/main/java/it/gov/pagopa/payments/controller/receipt/impl/PaymentsController.java
- src/main/java/it/gov/pagopa/payments/exception/AppError.java
- src/main/java/it/gov/pagopa/payments/mapper/ConvertTableEntityToReceiptModelResponse.java
- src/main/java/it/gov/pagopa/payments/model/PageInfo.java
- src/main/java/it/gov/pagopa/payments/model/PaymentsResult.java
- src/main/java/it/gov/pagopa/payments/service/PaymentsService.java
- src/main/java/it/gov/pagopa/payments/utils/CommonUtil.java
- src/test/java/it/gov/pagopa/payments/api/PaymentsControllerTest.java
- src/test/java/it/gov/pagopa/payments/service/PaymentsServiceTest.java
Adding new filter and total pages output when getting receipt list
Change needed for the correct implementation in the BO integration
Manually and through junit tests
> PAGOPA-1658 new filter and total pages output

- src/main/java/it/gov/pagopa/payments/service/PartnerService.java
> feat: add fiscalCodePA set with organizationFiscalCode

- .github/workflows/code_review.yml
- openapi/openapi.json
- src/main/java/it/gov/pagopa/payments/controller/receipt/IPaymentsController.java
- Add 403 error case to openapi spec.
This PR aims to add the 403 status code in OpenAPI for the APIs under the authorizer because this type of error may occur when the authorizer blocks the client's request.
> [PIDM-200] Add 403 error case to OpenAPI spec
